# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Thom Jordan
tagline:             ''
description:         ''
url:                 http://thomjordan.net
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Thom Jordan
  url:               https://twitter.com/t_h_o_m_j
  email:             thomjordan@gatech.edu

# Custom vars
version:             1.0.0
